<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://de.hub.clickwatch.compositionmodel/2.0" nsPrefix="compositemodelv2">
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//OutputEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelNode" eSuperTypes="#//DataNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="#//ActionNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//InputEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="#//ActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProgressEdge" eSuperTypes="#//Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ActionNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ActionNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="progressConnection" eType="#//ProgressEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataEdge" eSuperTypes="#//Edge"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputEdge" eSuperTypes="#//DataEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//DataNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Transformation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clickwatchModelElement"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputEdge" eSuperTypes="#//DataEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Transformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//DataNode"/>
  </eClassifiers>
</ecore:EPackage>
