//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.06 at 11:47:18 AM CEST 
//


package edu.hu.clickwatch.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="network" type="{}networkType" maxOccurs="unbounded"/>
 *         &lt;element name="cdo" type="{}cdoType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="logDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configurationType", propOrder = {
    "network",
    "cdo"
})
public class ConfigurationType {

    @XmlElement(required = true)
    protected List<NetworkType> network;
    @XmlElement(required = true)
    protected List<CdoType> cdo;
    @XmlAttribute
    protected String logDirectory;

    /**
     * Gets the value of the network property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the network property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetwork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkType }
     * 
     * 
     */
    public List<NetworkType> getNetwork() {
        if (network == null) {
            network = new ArrayList<NetworkType>();
        }
        return this.network;
    }

    /**
     * Gets the value of the cdo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cdo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCdo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CdoType }
     * 
     * 
     */
    public List<CdoType> getCdo() {
        if (cdo == null) {
            cdo = new ArrayList<CdoType>();
        }
        return this.cdo;
    }

    /**
     * Gets the value of the logDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogDirectory() {
        return logDirectory;
    }

    /**
     * Sets the value of the logDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogDirectory(String value) {
        this.logDirectory = value;
    }

}
