<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <eClassifiers xsi:type="ecore:EClass" name="RootClass">
    <eAnnotations source="http://de.hub.clickwatch.specificmodels">
      <details key="target_id" value="RootClass"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xml" eType="//Xml" volatile="true" transient="true" derived="true" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Xml">
    <eAnnotations source="http://de.hub.clickwatch.specificmodels">
      <details key="target_id" value="RootClass/xml|xml:Xml|EObject"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foo" eType="//Foo" volatile="true" transient="true" derived="true" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foo">
    <eAnnotations source="http://de.hub.clickwatch.specificmodels">
      <details key="target_id" value="RootClass/xml|xml:Xml|EObject/foo|foo:Foo|EObject"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" volatile="true" transient="true" derived="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
