<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SpecificCSMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="My Network">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1" eType="//Node" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="node"/>
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="all" eType="//MultiNode" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ElementFilter">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HandlerFilter">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updateIntervall">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subnetworks" upperBound="-1" eType="//Network" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="subnetwork"/>
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iNetAdress" defaultValueLiteral="localhost">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" defaultValueLiteral="7777">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1" eType="//Element" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="element"/>
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connected" transient="true" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connection" transient="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backbone" eType="//BackboneType" defaultValueLiteral="unknown"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retrieving" transient="true" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasRecord" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recording" transient="true" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gps" eType="//gps" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device_wifi" eType="//device_wifi" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1" eType="//Handler" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="handler"/>
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="watch" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="//Element" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Handler">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canRead">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canWrite">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changed" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="watch" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BackboneType">
    <eLiterals name="wired"/>
    <eLiterals name="wireless" value="1"/>
    <eLiterals name="unknown" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1" eType="//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="gps" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_Node" eType="//Node" eOpposite="//Node/gps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gps_coord" eType="//gps_coord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="long">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_gps_coord" eType="//gps_coord" eOpposite="//gps_coord/gps"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="gps_coord" eSuperTypes="//Handler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_gps" eType="//gps" eOpposite="//gps/gps_coord"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gps" eType="//gps" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="device_wifi" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_Node" eType="//Node" eOpposite="//Node/device_wifi"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rates" eType="//rates" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proberates" eType="//proberates" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="etx_metric" eType="//etx_metric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link_stat" eType="//link_stat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brnToMe" eType="//brnToMe" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wifidevice" eType="//wifidevice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_power" eType="//data_power" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_rate" eType="//data_rate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brnwifi" eType="//brnwifi" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_queue" eType="//data_queue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_suppressor" eType="//data_suppressor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lp_data_scheduler" eType="//lp_data_scheduler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter_tx" eType="//filter_tx" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="error_clf" eType="//error_clf" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wififrame_clf" eType="//wififrame_clf" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brn_ether_clf" eType="//brn_ether_clf" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lp_clf" eType="//lp_clf" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lp_etherencap" eType="//lp_etherencap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lp_power" eType="//lp_power" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lp_wifiencap" eType="//lp_wifiencap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lp_queue" eType="//lp_queue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lp_suppressor" eType="//lp_suppressor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rates" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/rates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="proberates" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/proberates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="etx_metric" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/etx_metric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="link_stat" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/link_stat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="brnToMe" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/brnToMe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="wifidevice" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/wifidevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cst" eType="//cst" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op_prio_s" eType="//op_prio_s" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ath_op" eType="//ath_op" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ath_op_q" eType="//ath_op_q" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dev_decap" eType="//dev_decap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawwifidev_too_small_cnt" eType="//rawwifidev_too_small_cnt" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="cst" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_wifidevice" eType="//wifidevice" eOpposite="//wifidevice/cst"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stats_xml" eType="//stats_xml" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stats" eType="//stats" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="stats_xml" eSuperTypes="//Handler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_cst" eType="//cst" eOpposite="//cst/stats_xml"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channelstats" eType="//channelstats" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="channelstats">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mac" eType="//mac" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mac_percentage" eType="//mac_percentage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mac_duration" eType="//mac_duration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phy" eType="//phy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbourstats" eType="//neighbourstats" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hw_duration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_stats_xml" eType="//stats_xml" eOpposite="//stats_xml/channelstats"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_stats" eType="//stats" eOpposite="//stats/channelstats"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mac">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packets">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_err_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crc_err_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phy_err_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unknown_err_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_unicast_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_retry_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_bcast_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_unicast_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_retry_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_bcast_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zero_err_pkt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last_packet_time">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_src">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_channelstats" eType="//channelstats" eOpposite="//channelstats/mac"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mac_percentage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="busy">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noerr_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crc_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phy_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unknown_err_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_channelstats" eType="//channelstats" eOpposite="//channelstats/mac_percentage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mac_duration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="busy">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noerr_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crc_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phy_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unknown_err_rx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_channelstats" eType="//channelstats" eOpposite="//channelstats/mac_duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="phy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hwbusy">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hwrx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hwtx">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last_hw_stat_time">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hw_stats_count">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avg_noise">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="std_noise">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avg_rssi">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="std_rssi">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="channel">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_channelstats" eType="//channelstats" eOpposite="//channelstats/phy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="neighbourstats">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nb" upperBound="-1" eType="//nb" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_channelstats" eType="//channelstats" eOpposite="//channelstats/neighbourstats"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="nb">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addr">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rssi">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="std_rssi">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_rssi">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_rssi">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pkt_cnt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_neighbourstats" eType="//neighbourstats" eOpposite="//neighbourstats/nb"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="stats" eSuperTypes="//Handler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_cst" eType="//cst" eOpposite="//cst/stats"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channelstats" eType="//channelstats" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="op_prio_s" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_wifidevice" eType="//wifidevice" eOpposite="//wifidevice/op_prio_s"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ath_op" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_wifidevice" eType="//wifidevice" eOpposite="//wifidevice/ath_op"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ath_op_q" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_wifidevice" eType="//wifidevice" eOpposite="//wifidevice/ath_op_q"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dev_decap" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_wifidevice" eType="//wifidevice" eOpposite="//wifidevice/dev_decap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rawwifidev_too_small_cnt" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_wifidevice" eType="//wifidevice" eOpposite="//wifidevice/rawwifidev_too_small_cnt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="data_power" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/data_power"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="data_rate" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/data_rate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="brnwifi" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/brnwifi"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="data_queue" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/data_queue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="data_suppressor" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/data_suppressor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lp_data_scheduler" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/lp_data_scheduler"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="filter_tx" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/filter_tx"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="error_clf" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/error_clf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="wififrame_clf" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/wififrame_clf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="brn_ether_clf" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/brn_ether_clf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lp_clf" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/lp_clf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lp_etherencap" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/lp_etherencap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lp_power" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/lp_power"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lp_wifiencap" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/lp_wifiencap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lp_queue" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/lp_queue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lp_suppressor" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainer_device_wifi" eType="//device_wifi" eOpposite="//device_wifi/lp_suppressor"/>
  </eClassifiers>
</ecore:EPackage>
