<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://compositionmodel/1.0" nsPrefix="comp">
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Edge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="#//Edge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationFunction"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//TransformationKind"
        defaultValueLiteral="predefined"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefinedTransformation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//ParameterSpec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//ParameterSpec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetSpec" eType="#//TargetSpec"
        defaultValueLiteral="add"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelNode" eSuperTypes="#//Node #//DataNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaModelResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inferedType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaModelClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registeredPackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSetNode" eSuperTypes="#//Node #//DataNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="#//DataSet"
        transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureNode" eSuperTypes="#//Node #//DataNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="#//Measure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedTransformation" eSuperTypes="#//Edge #//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visualization" eType="#//Visualization"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransformationKind">
    <eLiterals name="predefined"/>
    <eLiterals name="xtend" value="1"/>
    <eLiterals name="xpand" value="2"/>
    <eLiterals name="java" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ParameterSpecKind"
        defaultValueLiteral="root"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapClassKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TargetSpec">
    <eLiterals name="existing"/>
    <eLiterals name="add" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterSpecKind">
    <eLiterals name="root"/>
    <eLiterals name="map" value="1"/>
    <eLiterals name="list" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intValues" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleValues" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visualization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
